config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  get "tests", to: "home#tests"
  get "tests/*path", to: "home#tests"

  resources :rewards do
    collection do
      get :search
      get :search_rewards
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  extend Enumerize

  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/price.rb
class Price < ApplicationRecord

  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord

  has_many :prices
end

app/models/reward.rb
class Reward < ApplicationRecord
  enumerize :reward_type, in: [
    "集体",
    "个人",
  ], scope: true

  mount_uploader :file, RewardUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def tests
    gon.test_data = Util.test_data
    @no_header = true
  end
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  before_action :set_reward, only: [:show, :edit, :update, :destroy]

  # GET /rewards
  # GET /rewards.json
  def index
    @rewards = Reward.all
  end

  # GET /rewards/1
  # GET /rewards/1.json
  def show
  end

  # GET /rewards/new
  def new
    @reward = Reward.new
  end

  # GET /rewards/1/edit
  def edit
  end

  # POST /rewards
  # POST /rewards.json
  def create
    @reward = Reward.new(reward_params)
    if @reward.save
      redirect_to root_path
    else
      render :new
    end
  end

  # PATCH/PUT /rewards/1
  # PATCH/PUT /rewards/1.json
  # def update
  #   respond_to do |format|
  #     if @reward.update(reward_params)
  #       format.html { redirect_to @reward, notice: 'Reward was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @reward }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @reward.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /rewards/1
  # DELETE /rewards/1.json
  # def destroy
  #   @reward.destroy
  #   respond_to do |format|
  #     format.html { redirect_to rewards_url, notice: 'Reward was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  def search
  end

  def search_rewards
    q = params.require(:q).permit(
      :name,
      :person_name,
      :project_name,
    )
    reward_year = params[:q][:reward_at]

    rewards = Reward.where(q)
    date_from = Date.strptime(reward_year, "%Y") rescue nil
    if date_from
      rewards = rewards.where(reward_at: date_from...date_from.since(1.year))
    end
    render json: {
      html: (render_to_string partial: "table", locals: {rewards: rewards, type: params[:type]})
    }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reward
      @reward = Reward.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reward_params
      params.require(:reward).permit!
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/views/rewards/_form.html.slim
/ <%= form_for(reward) do |f| %>
/   <% if reward.errors.any? %>
/     <div id="error_explanation">
/       <h2><%= pluralize(reward.errors.count, "error") %> prohibited this reward from being saved:</h2>

/       <ul>
/       <% reward.errors.full_messages.each do |message| %>
/         <li><%= message %></li>
/       <% end %>
/       </ul>
/     </div>
/   <% end %>

/   <div class="actions">
/     <%= f.submit %>
/   </div>
/ <% end %>

= simple_form_for reward do |f|
  = f.input :name, label: "表彰名称"
  = f.input :reward_company, label: "表彰单位"
  = f.input :undertake_company, label: "承办单位"
  = f.input :reward_nature, label: "表彰性质"
  = f.input :reward_type, label: "集体/个人"
  .form-group
    label 表彰日期
    = f.date_field :reward_at, class: "form-control"
  / = f.input :reward_at, as: :date, label: "表彰日期"
  = f.input :file, label: "表彰文件"
  = f.input :person_name, label: "获奖人姓名"
  = f.input :person_gender, label: "获奖人性别"
  = f.input :person_work_info, label: "工作单位和职务"
  = f.input :person_salary, label: "享受待遇"
  = f.input :project_name, label: "获奖项目"
  = f.input :project_company, label: "主要完成单位"
  = f.input :project_member, label: "主要完成人"

  .right
    = f.submit "保存", class: "btn btn-primary"

scss:
  form {
    width: 600px;
    padding: 30px 0;
    .right {
      text-align: right;
    }
  }

app/views/rewards/_table.slim
/ rewards type
table.table.table-striped.table-hover
  - if type == "reward"
    thead
      tr
        td 表彰名称
        td 表彰时间
        td 表彰性质
        td 表彰单位
        td 承办单位
        td 集体/个人名额数
        td 获奖文件
    tbody
      - rewards.each do |reward|
        tr
          td = reward.name
          td = reward.reward_at.strftime("%F")
          td = reward.reward_nature
          td = reward.reward_company
          td = reward.undertake_company
          td = reward.project_company
          td
            - if reward.file.url
              = link_to "获奖文件", reward.file.url, target: "_blank"
  - elsif type == "person"
    thead
      tr
        td 获奖人姓名
        td 表彰名称
        td 表彰时间
        td 表彰性质
        td 表彰单位
        td 承办单位
        td 享受待遇
        td 单位职务
        td 表彰文件
    tbody
      - rewards.each do |reward|
        tr
          td = reward.person_name
          td = reward.name
          td = reward.reward_at.strftime("%F")
          td = reward.reward_nature
          td = reward.reward_company
          td = reward.undertake_company
          td = reward.person_salary
          td = reward.person_work_info
          td
            - if reward.file.url
              = link_to "获奖文件", reward.file.url, target: "_blank"

  - elsif type == "project"
    thead
      tr
        td 项目名称
        td 表彰名称
        td 表彰时间
        td 表彰性质
        td 表彰单位
        td 承办单位
        td 主要完成单位
        td 主要完成人
        td 表彰文件
    tbody
      - rewards.each do |reward|
        tr
          td = reward.project_name
          td = reward.name
          td = reward.reward_at.strftime("%F")
          td = reward.reward_nature
          td = reward.reward_company
          td = reward.undertake_company
          td = reward.project_company
          td = reward.project_member
          td
            - if reward.file.url
              = link_to "获奖文件", reward.file.url, target: "_blank"

app/views/rewards/edit.html.slim
<h1>Editing Reward</h1>

<%= render 'form', reward: @reward %>

<%= link_to 'Show', @reward %> |
<%= link_to 'Back', rewards_path %>

app/views/rewards/index.html.slim
<p id="notice"><%= notice %></p>

<h1>Rewards</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rewards.each do |reward| %>
      <tr>
        <td><%= link_to 'Show', reward %></td>
        <td><%= link_to 'Edit', edit_reward_path(reward) %></td>
        <td><%= link_to 'Destroy', reward, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reward', new_reward_path %>

app/views/rewards/new.html.slim
.container
  h1 新增奖励

  = render 'form', reward: @reward

app/views/rewards/search.slim
.container
  h1 查询奖励

  .panel.panel-default
    .panel-heading
      | 查询条件
    .panel-body
      .search-container data-search-type="reward"
        .search-field-wrapper
          label 奖励名称
          input.form-control data-param="name"
        .search-field-wrapper
          label 奖励年份
          input.form-control data-param="reward_at"
        .btn.btn-primary.search-button 查询
      .search-container data-search-type="person"
        .search-field-wrapper
          label 获奖人姓名
          input.form-control data-param="person_name"
        .btn.btn-primary.search-button 查询
      .search-container data-search-type="project"
        .search-field-wrapper
          label 获奖项目
          input.form-control data-param="project_name"
        .btn.btn-primary.search-button 查询

  .result-container

scss:
  .search-container {
    margin-bottom: 30px;
  }
  .search-field-wrapper {
    display: inline-block;
    width: 200px;
    margin-right: 20px;
  }

javascript:
  $(function(){
    $(".search-button").on("click", function() {
      var $container = $(this).parents(".search-container"),
          params = {
            q: {},
            type: $container.data("search-type")
          };

      $container.find("input").each(function(index, ele){
        var $ele = $(ele),
            key  = $ele.data("param"),
            value = $ele.val();
        if (value !== "") {
          params.q[key] = value;
        }
      });
      if (Object.keys(params.q).length > 0) {
        $.get("search_rewards", params).done(function(ret){
          $(".result-container").html(ret.html);
        });
      }
    });
  })

app/views/rewards/show.html.slim
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_reward_path(@reward) %> |
<%= link_to 'Back', rewards_path %>