config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  get "tests", to: "home#tests"
  get "tests/*path", to: "home#tests"

  resources :rewards do
    collection do
      get :search
      get :search_rewards
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  extend Enumerize

  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/price.rb
class Price < ApplicationRecord

  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord

  has_many :prices
end

app/models/reward.rb
class Reward < ApplicationRecord
  enumerize :reward_type, in: [
    "集体",
    "个人",
  ], scope: true

  mount_uploader :file, RewardUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def tests
    gon.test_data = Util.test_data
    @no_header = true
  end
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  before_action :set_reward, only: [:show, :edit, :update, :destroy]

  # GET /rewards
  # GET /rewards.json
  def index
    @rewards = Reward.all
  end

  # GET /rewards/1
  # GET /rewards/1.json
  def show
  end

  # GET /rewards/new
  def new
    @reward = Reward.new
  end

  # GET /rewards/1/edit
  def edit
  end

  # POST /rewards
  # POST /rewards.json
  def create
    @reward = Reward.new(reward_params)
    if @reward.save
      redirect_to root_path
    else
      render :new
    end
  end

  # PATCH/PUT /rewards/1
  # PATCH/PUT /rewards/1.json
  # def update
  #   respond_to do |format|
  #     if @reward.update(reward_params)
  #       format.html { redirect_to @reward, notice: 'Reward was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @reward }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @reward.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /rewards/1
  # DELETE /rewards/1.json
  # def destroy
  #   @reward.destroy
  #   respond_to do |format|
  #     format.html { redirect_to rewards_url, notice: 'Reward was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  def search
  end

  def search_rewards
    q = params.require(:q).permit(
      :name,
      :person_name,
      :project_name,
    )
    reward_year = params[:q][:reward_at]

    rewards = Reward.where(q)
    date_from = Date.strptime(reward_year, "%Y") rescue nil
    if date_from
      rewards = rewards.where(reward_at: date_from...date_from.since(1.year))
    end
    render json: {
      html: (render_to_string partial: "table", locals: {rewards: rewards, type: params[:type]})
    }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reward
      @reward = Reward.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reward_params
      params.require(:reward).permit!
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/views/home/index.slim
.container
  .panel.panel-default
    .panel-heading
      | 新增查询系统DEMO
    .panel-body
      = link_to new_reward_path do ||
        .btn.btn-primary
          | 新增
      = link_to search_rewards_path do ||
        .btn.btn-primary style="margin-left: 100px;"
          | 查询

scss:
  .panel {
    width: 600px;
    margin: 30px auto;
  }

  .panel-heading {
    text-align: center;
    font-size: 20px;
  }

  .panel-body {
    margin-top: 30px;
    text-align: center;
    .btn {
      width: 100px;
    }
  }

app/views/home/tests.slim
#main-root v-cloak=true
  router-view


template#entry-index-template
  #entry-index
    .title
      | 请测试您的肤质:
    .subtitle
      | 根据选择提供精准服务
    template (
      v-for="(test, index) in tests"
    )
      router-link :to="(index + 1) + '/questions/1'"
        .entry-block
          .test-title
            | {{ test.title }}
          /.desc
            | {{ test.desc}}
          /.answer
            | {{ $root.result(test) }}

template#test-show-template
  #test-show
    .header
      router-link to="/"
        .back
          i.fa.fa-chevron-left
      | {{ test.title }}
    router-view

template#question-show-template
  #question-show
    .question
      | {{ question.question}}
    .options
      .option (
        v-for="(option, index) in question.answers"
        @click="select_option(index)"
      )
        i.fa (
          :class="question.checked_index === index ? 'fa-check-circle-o' : 'fa-circle-thin'"
        )
        span
          | {{ option }}
    router-link v-if="!is_first" :to="prev_question_link"
      .custom-btn.prev-question
        | 上一题
    / router-link v-if="!is_last" :to="next_question_link"
    /   .btn.btn-primary
    /     | 下一题

template#test-result
  .result-container
    .result
      | {{ "测试结果： " + result }}
    router-link to="/"
      .custom-btn
        | 继续其他测试



javascript:
  $(function() {
    var Index = {
      template: "#entry-index-template",
      data () {
        return {
          tests: this.$root.tests
        }
      }
    }

    var Test = {
      template: "#test-show-template",
      props: ["test_id"],
      data () {
        return {
          test: this.$root.tests[this.test_id * 1 - 1]
        }
      }
    }

    var Question = {
      template: "#question-show-template",
      props: [
        "test_id",
        "question_id",
      ],
      data () {
        return {
          timeout_id: null
        }
      },
      computed: {
        // ID 从 1 开始
        parsed_question_id () {
          return this.question_id * 1;
        },
        questions () {
          return this.$parent.test.questions;
        },
        question () {
          return this.questions[this.parsed_question_id - 1];
        },
        is_first () {
          return this.parsed_question_id === 1;
        },
        is_last () {
          return this.parsed_question_id === this.questions.length;
        },
        prev_question_link () {
          return (this.parsed_question_id - 1) + "";
        },
        next_question_link () {
          return (this.parsed_question_id + 1) + "";
        },
        result_link () {
          return "/" + this.test_id + "/result";
        }
      },
      methods: {
        select_option (index) {
          clearTimeout(this.timeout_id);
          this.question.checked_index = index;
          this.timeout_id = setTimeout(() => {
            if (this.is_last) {
              this.$router.push(this.result_link);
            } else {
              this.$router.push(this.next_question_link);
            }
          }, 200);
        }
      },
    }

    var Result = {
      template: "#test-result",
      computed: {
        test () {
          return this.$parent.test;
        },
        result () {
          return this.$root.result(this.test);
        }
      },
    }

    var NotFound = {
      template: "<div>Not Found</div>"
    }

    var router = new VueRouter({
      mode: 'history',
      base: '/tests',
      routes: [
        { path: '/', component: Index },
        {
          path: '/:test_id',
          component: Test,
          props: true,
          children: [
            { path: 'questions/:question_id', component: Question, props: true },
            { path: 'result', component: Result },
          ]
        },
        { path: '*', component: NotFound },
      ]
    });

    gon.test_data.forEach( test => {
      test.forEach( question => {
        question.checked_index = null;
      });
    });

    new Vue({
      data: {
        scores: [1, 2, 3, 4, 2.5],
        selected_test: null,
        tests: [
          {
            title: "干性皮肤 vs 油性皮肤",
            desc: "通过回答这部分的问题，可以准确分析出皮肤的含水状况和出油程度。研究表明，虽然许多人对于自己属于油性或干性皮肤显得很确定，但其实这些预见往往并不准确。别让自己的那些成见或主观臆断影响你的回答，只要根据实际情况来选择就对了。",
            questions: gon.test_data[0],
            summary: [
              [16, "非常干的皮肤"],
              [26, "轻微的干性皮肤"],
              [33, "轻微的油性皮肤"],
              [44, "非常油的皮肤"],
            ]
          }, {
            title: "敏感性皮肤 vs 耐受性皮肤",
            desc: "通过回答这部分的问题，可以准确分析出你的皮肤趋向于发生各种敏感肌肤症状的程度，所有的面疱（痤疮/痘痘）、红肿、潮红、发痒都属于皮肤的敏感症状。",
            questions: gon.test_data[1],
            summary: [
              [24, "耐受性很强的皮肤"],
              [29, "比较有耐受性的皮肤 "],
              [33, "轻微的油性皮肤"],
              [72, "非常油的皮肤"],
            ]
          }, {
            title: "色素沉着性皮肤 vs 非色素沉着性皮肤",
            desc: "通过回答这部分的问题，测试你是否有形成黑色素的倾向。黑色素会使你受到日晒后的皮肤出现黑斑、雀斑以及一些深色区域。反过来说，黑色素的生成也是皮肤自我保护的反应，它会通过使肤色变深来保护你不被晒伤。",
            questions: gon.test_data[2],
            summary: [
              [30, "非色素沉着性皮肤（简称“非”型或N Type）"],
              [45, "色素沉着性皮肤（简称“色”型或P Type）"],
            ]
          }, {
            title: "皱纹性皮肤 vs 紧致性皮肤",
            desc: "通过回答这部分的问题，可以准确分析出你的皮肤是否属于容易生出皱纹的类型，以及你现在的已经出现的皱纹危机。",
            questions: gon.test_data[3],
            summary: [
              [40, "紧致性皮肤（简称“紧”型或T Type）"],
              [85, "皱纹性皮肤（简称“皱”型或W Type）"],
            ]
          }
        ]
      },
      computed: {
        current_question () {
          return this.$route.params.index;
        }
      },
      methods: {
        is_finished (test) {
          return test.questions.filter((question) => {
            return question.checked_index === null
          }).length === 0;
        },
        score (test) {
          let score = 0;
          test.questions.forEach((question) => {
            score += this.$root.scores[question.checked_index]
          })
          return score;
        },
        result (test) {
          if (this.is_finished(test)) {
            let result = "",
                score = this.score(test);
            $.each(test.summary, (index, value) => {
              if ( score < value[0]) {
                result = value[1];
                return false;
              }
            });
            return result;
          } else {
            return "尚未完成答题";
          }
        }
      },
      router,
    }).$mount("#main-root")
  })

- content_for :page_css
  = stylesheet_link_tag 'pages/tests'